name = "wba-signed-cards"
main = "build/index.js"
compatibility_date = "2025-12-11"

kv_namespaces = [
    {"binding" = "signed-agent-registry-hostnames"},
]

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"